version: '3.3'
services:
    web:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ${PWD}:/code
            - ${PWD}/docker/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
            - mysql
            - redis
    php:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - ${PWD}:/code
        links:
            - mysql
    node:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.node
        volumes:
            - ${PWD}:/code
    mysql:
        image: mysql:5.6
        ports:
            - "3307:3306"
        volumes: 
            - ./volumes/mysql:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: "sgepme@123"
            MYSQL_DATABASE: "sgpme_db"
    redis:
        image: redis
        ports:
            - "6379:6379"